package scanner;

public enum Tokens {
    INTEGER, HEX, RADIX, REAL, LIT_NAME, EXEC_NAME, OPERATOR, STRINGS,
    OPEN_SQUARE_BRACKET, CLOSE_SQUARE_BRACKET, OPEN_CURLY_BRACE,
    CLOSE_CURLY_BRACE, OPEN_CHEVRON_BRACKET, CLOSE_CHEVRON_BRACKET, COMMENTS,
    STRING_TEXT
}
