/* The following code was generated by JFlex 1.6.0 */

package scanner;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>/home/user/dev/postscript-in-jvm/bytecode/postscript-in-jvm/parser/src/main/java/scanner/ps.flex</tt>
 */
public class Yylex {
    private boolean need_garbage = false;

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;

    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;
    private static final String ZZ_NL = System.getProperty("line.separator");

    /**
     * lexical states
     */
    public static final int YYINITIAL = 0;
    public static final int COMMENT = 2;
    public static final int YYSTRING = 4;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0, 1, 1, 2, 2
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\10\0\2\13\1\11\1\0\1\14\1\12\22\0\1\13\2\0\1\25" +
                    "\1\0\1\10\2\0\1\26\1\7\1\0\1\3\1\0\1\3\1\4" +
                    "\1\15\12\1\2\0\1\22\1\0\1\23\2\0\1\2\1\2\1\2" +
                    "\1\2\1\5\1\2\1\0\1\0\1\0\2\0\1\0\1\0\1\0" +
                    "\1\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0\3\0" +
                    "\1\16\1\6\1\17\1\0\1\0\1\0\1\2\1\2\2\2\1\5" +
                    "\1\2\7\0\1\0\3\0\1\0\1\0\1\0\6\0\1\20\1\0" +
                    "\1\21\1\24\6\0\1\0\u1fa2\0\1\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\1\1\1\2\1\3\1\4\2\3\1\5\1\6" +
                    "\2\7\1\5\1\10\1\11\1\12\1\13\2\5\1\14" +
                    "\1\15\1\7\1\1\1\2\1\16\1\17\1\20\2\3" +
                    "\1\4\1\7\1\21\2\0\1\22\1\23\1\0\1\24" +
                    "\1\20\1\3\1\25\1\26\1\0\1\27";

    private static int[] zzUnpackAction() {
        int[] result = new int[43];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\27\0\56\0\105\0\134\0\163\0\212\0\241" +
                    "\0\241\0\270\0\317\0\346\0\241\0\241\0\241\0\241" +
                    "\0\375\0\u0114\0\241\0\u012b\0\u012b\0\u0142\0\u0159\0\241" +
                    "\0\241\0\u0170\0\u0187\0\u019e\0\u01b5\0\241\0\u01cc\0\u01e3" +
                    "\0\u01fa\0\241\0\241\0\u0211\0\241\0\u0228\0\u0228\0\u019e" +
                    "\0\u01e3\0\u023f\0\u0211";

    private static int[] zzUnpackRowMap() {
        int[] result = new int[43];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\4\1\5\1\4\1\6\1\7\1\4\2\10\1\11" +
                    "\1\12\1\13\1\12\1\0\1\14\1\15\1\16\1\17" +
                    "\1\20\1\21\1\22\2\4\1\23\10\24\1\25\2\26" +
                    "\14\24\7\27\1\30\16\27\1\31\6\4\16\0\2\4" +
                    "\1\0\1\4\1\5\2\4\1\32\1\33\16\0\1\4" +
                    "\1\34\1\0\1\4\1\35\2\4\1\7\1\4\16\0" +
                    "\2\4\1\0\1\4\1\32\4\4\16\0\2\4\41\0" +
                    "\1\12\1\0\1\12\24\0\1\36\15\0\6\37\7\0" +
                    "\1\40\6\0\2\37\2\0\2\41\2\0\1\41\14\0" +
                    "\1\42\1\43\1\44\25\0\1\45\3\0\11\24\2\0" +
                    "\14\24\11\0\2\26\14\0\7\27\1\0\16\27\1\0" +
                    "\1\4\1\32\3\4\1\33\16\0\2\4\1\0\1\4" +
                    "\1\46\1\4\1\47\2\4\16\0\2\4\1\0\1\4" +
                    "\1\50\4\4\16\0\2\4\1\0\1\4\1\35\2\4" +
                    "\1\32\1\33\16\0\2\4\1\0\6\37\16\0\2\37" +
                    "\1\0\6\51\16\0\2\51\2\0\2\41\2\0\1\41" +
                    "\15\0\1\43\3\0\7\44\1\0\14\44\1\52\1\44" +
                    "\1\0\1\4\1\46\4\4\16\0\2\4\1\0\7\44" +
                    "\1\0\13\44\1\53\1\52\1\44\1\0";

    private static int[] zzUnpackTrans() {
        int[] result = new int[598];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\6\1\2\11\3\1\4\11\2\1\1\11\4\1" +
                    "\2\11\4\1\1\11\1\1\2\0\2\11\1\0\1\11" +
                    "\4\1\1\0\1\1";

    private static int[] zzUnpackAttribute() {
        int[] result = new int[43];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * the input device
     */
    private java.io.Reader zzReader;

    /**
     * the current state of the DFA
     */
    private int zzState;

    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;

    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;

    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;

    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;

    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;

    /**
     * The number of occupied positions in zzBuffer beyond zzEndRead.
     * When a lead/high surrogate has been read from the input stream
     * into the final zzBuffer position, this will have a value of 1;
     * otherwise, it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /* user code: */
    private int string_depth = 0;
    private int proc_depth = 0;
    private String curString = "";


    public int getProcDepth() {
        return proc_depth;
    }


    /**
     * Creates a new scanner
     *
     * @param in the java.io.Reader to read input from.
     */
    public Yylex(java.io.Reader in) {
        this.zzReader = in;
    }


    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x110000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 188) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }

    private static String zzToPrintable(String str) {
        StringBuilder builder = new StringBuilder();
        for (int n = 0; n < str.length(); ) {
            int ch = str.codePointAt(n);
            int charCount = Character.charCount(ch);
            n += charCount;
            if (ch > 31 && ch < 127) {
                builder.append((char) ch);
            } else if (charCount == 1) {
                builder.append(String.format("\\u%04X", ch));
            } else {
                builder.append(String.format("\\U%06X", ch));
            }
        }
        return builder.toString();
    }


    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

      /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

    /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
            char newBuffer[] = new char[zzBuffer.length * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
        }

    /* fill the buffer with new input */
        int requested = zzBuffer.length - zzEndRead;
        int totalRead = 0;
        while (totalRead < requested) {
            int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
            if (numRead == -1) {
                break;
            }
            totalRead += numRead;
        }

        if (totalRead > 0) {
            zzEndRead += totalRead;
            if (totalRead == requested) { /* possibly more input available */
                if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                    --zzEndRead;
                    zzFinalHighSurrogate = 1;
                }
            }
            return false;
        }

        // totalRead = 0: End of stream
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     * <p/>
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     * <p/>
     * Internal scan buffer is resized down to its initial length, if it has grown.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        zzFinalHighSurrogate = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
        if (zzBuffer.length > ZZ_BUFFERSIZE)
            zzBuffer = new char[ZZ_BUFFERSIZE];
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p/>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p/>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p/>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p/>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public Yytoken yylex() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            yychar += zzMarkedPosL - zzStartRead;

            boolean zzR = false;
            int zzCh;
            int zzCharCount;
            for (zzCurrentPosL = zzStartRead;
                 zzCurrentPosL < zzMarkedPosL;
                 zzCurrentPosL += zzCharCount) {
                zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
                zzCharCount = Character.charCount(zzCh);
                switch (zzCh) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                        }
                        break;
                    default:
                        zzR = false;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ((zzAttributes & 1) == 1) {
                zzAction = zzState;
            }


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    } else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 1:
//          System.out.println("line: "+(yyline+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
//          System.out.println("action [110] { yybegin(YYINITIAL); }");
                {
                    yybegin(YYINITIAL);
                }
                case 24:
                    break;
                case 2:
//          System.out.println("line: "+(yyline+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
//          System.out.println("action [126] { String text = yytext();"+ZZ_NL+"                //todo"+ZZ_NL+"                //curString = curString + text.substring(yychar,yychar+yylength());"+ZZ_NL+"                curString = curString + text.substring(0,text.length()); }");
                {
                    String text = yytext();
                    //todo
                    //curString = curString + text.substring(yychar,yychar+yylength());
                    curString = curString + text.substring(0, text.length());
                }
                case 25:
                    break;
                case 3:
//          System.out.println("line: "+(yyline+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
//          System.out.println("action [93] { return (new Yytoken(Tokens.EXEC_NAME,yytext(),yyline,yychar,yychar+yylength())); }");
                {
                    return (new Yytoken(Tokens.EXEC_NAME, yytext(), yyline, yychar, yychar + yylength()));
                }
                case 26:
                    break;
                case 4:
//          System.out.println("line: "+(yyline+1)+" "+"match: --"+zzToPrintable(yytext())+"--");
//          System.out.println("action [67] { return (new Yytoken(Tokens.INTEGER,yytext(),yyline,yychar,yychar+yylength())); }");
                {
                    return (new Yytoken(Tokens.INTEGER, yytext(), yyline, yychar, yychar + yylength()));
                }
                case 27:
                    break;
                case 5:
                    if (need_garbage) {
                        System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
                        System.out.println("action [135] { System.out.println(\"Illegal character: <\" + yytext() + \">\");" + ZZ_NL + "\tUtility.error(Utility.E_UNMATCHED); }");
                    }
                {
                    if (need_garbage) {
                        System.out.println("Illegal character: <" + yytext() + ">");
                    }
                    Utility.error(Utility.E_UNMATCHED);
                }
                case 28:
                    break;
                case 6:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [82] { yybegin(COMMENT); }");
                {
                    yybegin(COMMENT);
                }
                case 29:
                    break;
                case 7:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [80] {  }");
                {
                }
                case 30:
                    break;
                case 8:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [50] { return (new Yytoken(Tokens.OPEN_SQUARE_BRACKET,yytext(),yyline,yychar,yychar+1)); }");
                {
                    return (new Yytoken(Tokens.OPEN_SQUARE_BRACKET, yytext(), yyline, yychar, yychar + 1));
                }
                case 31:
                    break;
                case 9:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [51] { return (new Yytoken(Tokens.CLOSE_SQUARE_BRACKET,yytext(),yyline,yychar,yychar+1)); }");
                {
                    return (new Yytoken(Tokens.CLOSE_SQUARE_BRACKET, yytext(), yyline, yychar, yychar + 1));
                }
                case 32:
                    break;
                case 10:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [53] { proc_depth++;" + ZZ_NL + "            return (new Yytoken(Tokens.OPEN_CURLY_BRACE,yytext(),yyline,yychar,yychar+1)); }");
                {
                    proc_depth++;
                    return (new Yytoken(Tokens.OPEN_CURLY_BRACE, yytext(), yyline, yychar, yychar + 1));
                }
                case 33:
                    break;
                case 11:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [57] { if (--proc_depth < 0) {" + ZZ_NL + "            System.out.println(\"Error\");" + ZZ_NL + "            System.exit(-1);" + ZZ_NL + "         }" + ZZ_NL + "         return new Yytoken(Tokens.CLOSE_CURLY_BRACE,yytext(),yyline,yychar,yychar+1); }");
                {
                    if (--proc_depth < 0) {
                        System.out.println("Error");
                        System.exit(-1);
                    }
                    return new Yytoken(Tokens.CLOSE_CURLY_BRACE, yytext(), yyline, yychar, yychar + 1);
                }
                case 34:
                    break;
                case 12:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [84] { curString =  \"\";" + ZZ_NL + "    string_depth = 1;" + ZZ_NL + "    yybegin(YYSTRING); }");
                {
                    curString = "";
                    string_depth = 1;
                    yybegin(YYSTRING);
                }
                case 35:
                    break;
                case 13:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [111] { return (new Yytoken(Tokens.COMMENTS,yytext(),yyline,yychar,yychar+yylength())); }");
                {
                    return (new Yytoken(Tokens.COMMENTS, yytext(), yyline, yychar, yychar + yylength()));
                }
                case 36:
                    break;
                case 14:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [119] { if (--string_depth == 0) {" + ZZ_NL + "            yybegin(YYINITIAL);" + ZZ_NL + "            return (new Yytoken(Tokens.STRINGS,curString,yyline,0,curString.length()));" + ZZ_NL + "            } else {" + ZZ_NL + "            curString = curString+ \")\";" + ZZ_NL + "         } }");
                {
                    if (--string_depth == 0) {
                        yybegin(YYINITIAL);
                        return (new Yytoken(Tokens.STRINGS, curString, yyline, 0, curString.length()));
                    } else {
                        curString = curString + ")";
                    }
                }
                case 37:
                    break;
                case 15:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [116] { string_depth++;" + ZZ_NL + "       curString = curString + \"(\"; }");
                {
                    string_depth++;
                    curString = curString + "(";
                }
                case 38:
                    break;
                case 16:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [78] { return(new Yytoken(Tokens.REAL,yytext(),yyline,yychar,yychar+yylength())); }");
                {
                    return (new Yytoken(Tokens.REAL, yytext(), yyline, yychar, yychar + yylength()));
                }
                case 39:
                    break;
                case 17:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [95] { String text =yytext().substring(1);" + ZZ_NL + "          return (new Yytoken(Tokens.LIT_NAME,text,yyline,yychar+1,yychar+yylength())); }");
                {
                    String text = yytext().substring(1);
                    return (new Yytoken(Tokens.LIT_NAME, text, yyline, yychar + 1, yychar + yylength()));
                }
                case 40:
                    break;
                case 18:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [64] { return (new Yytoken(Tokens.OPEN_CHEVRON_BRACKET,yytext(),yyline,yychar,yychar+1)); }");
                {
                    return (new Yytoken(Tokens.OPEN_CHEVRON_BRACKET, yytext(), yyline, yychar, yychar + 1));
                }
                case 41:
                    break;
                case 19:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [69] { String text = yytext().substring(1,yytext().length()-2);" + ZZ_NL + "return (new Yytoken(Tokens.HEX,text,yyline,yychar,yychar+yylength())); }");
                {
                    String text = yytext().substring(1, yytext().length() - 2);
                    return (new Yytoken(Tokens.HEX, text, yyline, yychar, yychar + yylength()));
                }
                case 42:
                    break;
                case 20:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [65] { return (new Yytoken(Tokens.CLOSE_CHEVRON_BRACKET,yytext(),yyline,yychar,yychar+1)); }");
                {
                    return (new Yytoken(Tokens.CLOSE_CHEVRON_BRACKET, yytext(), yyline, yychar, yychar + 1));
                }
                case 43:
                    break;
                case 21:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [76] { return (new Yytoken(Tokens.RADIX,yytext(),yyline,yychar,yychar+yylength())); }");
                {
                    return (new Yytoken(Tokens.RADIX, yytext(), yyline, yychar, yychar + yylength()));
                }
                case 44:
                    break;
                case 22:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [99] { String text = yytext().substring(2);" + ZZ_NL + "            return (new Yytoken(Tokens.OPERATOR,text,yyline,yychar+2,yychar+yylength())); }");
                {
                    String text = yytext().substring(2);
                    return (new Yytoken(Tokens.OPERATOR, text, yyline, yychar + 2, yychar + yylength()));
                }
                case 45:
                    break;
                case 23:
//                    System.out.println("line: " + (yyline + 1) + " " + "match: --" + zzToPrintable(yytext()) + "--");
//                    System.out.println("action [73] { return (new Yytoken(Tokens.STRING_TEXT,yytext(),yyline,yychar+2,yychar+yylength()-2)); }");
                {
                    return (new Yytoken(Tokens.STRING_TEXT, yytext(), yyline, yychar + 2, yychar + yylength() - 2));
                }
                case 46:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        return null;
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }

    /**
     * Runs the scanner on input files.
     * <p/>
     * This main method is the debugging routine for the scanner.
     * It prints debugging information about each returned token to
     * System.out until the end of file is reached, or an error occured.
     *
     * @param argv the command line, contains the filenames to run
     *             the scanner on.
     */
    public static void main(String argv[]) {
        if (argv.length == 0) {
            System.out.println("Usage : java Yylex [ --encoding <name> ] <inputfile(s)>");
        } else {
            int firstFilePos = 0;
            String encodingName = "UTF-8";
            if (argv[0].equals("--encoding")) {
                firstFilePos = 2;
                encodingName = argv[1];
                try {
                    java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
                } catch (Exception e) {
                    System.out.println("Invalid encoding '" + encodingName + "'");
                    return;
                }
            }
            for (int i = firstFilePos; i < argv.length; i++) {
                Yylex scanner = null;
                try {
                    java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
                    java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
                    scanner = new Yylex(reader);
                    do {
                        System.out.println(scanner.yylex());
                    } while (!scanner.zzAtEOF);

                } catch (java.io.FileNotFoundException e) {
                    System.out.println("File not found : \"" + argv[i] + "\"");
                } catch (java.io.IOException e) {
                    System.out.println("IO error scanning file \"" + argv[i] + "\"");
                    System.out.println(e);
                } catch (Exception e) {
                    System.out.println("Unexpected exception:");
                    e.printStackTrace();
                }
            }
        }
    }


}
