package runtime.events;

/**
 * Created by User on 16/2/2015.
 */
public enum EventType {
    CLICK, DOUBLE_CLICK, RELEASE, PRESS, RESIZE, MOVE, DRAG, CLOSE, ENTER, EXIT, RIGHT_CLICK, PAINT, KEYBOARD_CHAR, USER, UPDATE_VALUE, KEYBOARD_CONTROL

}
